mfdw_site/mfdw_site/urls.py
from django.views.generic.base import TemplateView
from quotes.views import Register
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('testpage', TemplateView.as_view(template_name='pages/page.html')),
    path('admin/', admin.site.urls),
    path('register/success', TemplateView.as_view(template_name="registration/success.html"), name='register-success'),
    path('register/', Register.as_view(), name='register'),
    path('quote/', include('quotes.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('pages.urls')),
]

mfdw_site/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
#    path('', views.index, name='index'),
    path('', views.index, {'pagename': ''}, name='home'),
    path('contact', views.contact, name='contact'),
    path('<str:pagename>', views.index, name='index'),

]

mfdw_site/quotes/urls.py
from django.urls import path

from . import views
from .views import QuoteList, QuoteView

urlpatterns = [
    path('', views.quote_req, name='quote-request'),
    path('show/<int:pk>', QuoteView.as_view(), name='quote-detail'),
    path('show', QuoteList.as_view(), name='show-quotes'),
]

mfdw_site/pages/models.py
from django.db import models

class Page(models.Model):
    title = models.CharField(max_length=60)
    permalink = models.CharField(max_length=12, unique=True)
    update_date = models.DateTimeField('Last Updated')
    bodytext = models.TextField('Page Content', blank=True)

    def __str__(self):
        return self.title

mfdw_site/quotes/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS_CHOICES = (
    ('NEW', 'New Site'),
    ('EX', 'Existing Site'),
)

PRIORITY_CHOICES = (
    ('U', 'Urgent - 1 week or less'),
    ('N', 'Normal - 2 to 4 weeks'),
    ('L', 'Low - Still researching'),
)

class Quote(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=60, blank=True)
    company = models.CharField(max_length=60, blank=True)
    address = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=30, blank=True)
    email = models.EmailField()
    web = models.URLField(blank=True)
    description = models.TextField()
    sitestatus = models.CharField(max_length=20, choices=STATUS_CHOICES)
    priority = models.CharField(max_length=40, choices=PRIORITY_CHOICES)
    jobfile = models.FileField(upload_to='uploads/', blank=True)
    submitted = models.DateField(blank=True, null=True)
    quotedate = models.DateField(blank=True, null=True)
    quoteprice = models.DecimalField(decimal_places=2, max_digits=7, blank=True, default=0)
    username = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

mfdw_site/pages/forms.py
from django import forms

class ContactForm(forms.Form):
    yourname = forms.CharField(max_length=100, label='Your Name')
    email = forms.EmailField(required=False, label='Your e-mail address')
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

mfdw_site/quotes/forms.py
from django import forms
from django.forms import ModelForm
from .models import Quote

class QuoteForm(ModelForm):
    required_css_class = 'required'
    class Meta:
        model = Quote
        fields = [
            'name', 'position', 'company', 'address',
            'phone', 'email', 'web', 'description',
            'sitestatus', 'priority', 'jobfile'
        ]

mfdw_site/pages/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.mail import send_mail, get_connection

from . models import Page
from .forms import ContactForm

def index(request, pagename):
    pagename = '/' + pagename
    pg = get_object_or_404(Page, permalink=pagename)
    context = {
        'title': pg.title,
        'content': pg.bodytext,
        'last_updated': pg.update_date,
        'page_list': Page.objects.all(),
        }
    # assert False
    return render(request, 'pages/page.html', context)

def contact(request):
    submitted = False
    if request.method =='POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            #  assert False
            con = get_connection('django.core.mail.backends.console.EmailBackend')
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
                connection=con
            )
            return HttpResponseRedirect('/contact?submitted=True')
    else:
        form = ContactForm()
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'pages/contact.html', {'form': form, 'page_list': Page.objects.all(), 'submitted': submitted})

mfdw_site/quotes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Quote
from .forms import QuoteForm
from pages.models import Page

class Register(CreateView):
    template_name= 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register-success')

    def form_valid(self, form):
        form.save()
        return HttpResponseRedirect(self.success_url)

class QuoteView(LoginRequiredMixin, DetailView):
    #model = Quote
    context_object_name = 'quote'

    def get_queryset(self):
        return Quote.objects.filter(username=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(QuoteView, self).get_context_data(**kwargs)
        context['page_list'] = Page.objects.all()
        return context

class QuoteList(LoginRequiredMixin, ListView):
    #model = Quote
    context_object_name = 'all_quotes'

    def get_queryset(self):
        return Quote.objects.filter(username=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(QuoteList, self).get_context_data(**kwargs)
        context['page_list'] = Page.objects.all()
        return context

def quote_req(request):
    submitted = False
    if request.method == 'POST':
        form = QuoteForm(request.POST, request.FILES)


        if form.is_valid():
            form.save(commit=False)
            try:
                quote.username = request.user
            except Exeption:
                pass
            quote.save()
            return HttpResponseRedirect('/quote/?submitted=True')
    else:
        form = QuoteForm()
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'quotes/quote.html', {'form': form, 'page_list': Page.objects.all(), 'submitted': submitted})

mfdw_site/mfdw_site/templates/base.html
{% load static %}
<!doctype html>
<html>
<head>
<link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}"/>
<meta charset="utf-8">
<title>
  {% block title %}
    Untitled Document
  {% endblock title %}
</title>
<link href="{% static 'main.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
<div id="wrapper">
  <header id="wrapper">
    <div id="logo"><img src="{% static 'logo.jpg' %}" width="64" height="64" alt=""/>
      <span style="float: right;">
        {% if user.is_authenticated %}
          Hello, {{ user.username }}. <a href="{% url 'logout' %}?next=/">Log out</a>.
        {% else %}
          Not logged in. <a href="{% url 'login' %}">Log in</a>
        {% endif %}
      </span>
    </div>
    <div id="topbanner"><img src="{% static 'pngwave.png' %}" width="800" height="200" alt=""/><div>
  </header>
  <aside id="leftsidebar">
    <nav id="nav">
      <ul>
        {% block sidenav %}
        <li>Menu 1</li><li>Menu 2</li><li>Menu 3</li>
        {% endblock sidenav %}
        <li><a href="/contact">Contact Us</a></li>
        <li><a href="/quote/">Get a Quote</a></li>
        <li><a href="/quote/show">Show Quotes</a></li>
      </ul>
    </nav>
  </aside>
  <section id="main">
    {% block content %}
      <h1>Welcome!</h1>
      <p>This is the site template</p>
    {% endblock content %}
  </section>
  <footer id="footer">Copyright &copy; 2020 Z-pike refinery</footer>
</div>
</body>
</html>

mfdw_site/pages/templates/pages/contact.html
{% extends "pages/page.html" %}

{% block title %}Contact Us{% endblock title %}

{% block content %}
<h1>Contact us</h1>

{% if submitted %}
  <p class = "success">
    Your message was submitted successfully. Thank you.
  </p>

{% else %}
  <form action="" method="post" novalidate>
  <table>
    {{ form.as_table }}
    <tr>
      <td>&nbsp;</td>
      <td><input type="submit" value="Submit"></td>
    </tr>
  </table>
  {% csrf_token %}
  </form>
{% endif %}
{% endblock content %}

mfdw_site/pages/templates/pages/page.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock title %}

  {% block sidenav %}
    {% for page in page_list %}
    <li>
      <a href="{{ page.permalink }}">{{ page.title }}</a>
    </li>
    {% endfor %}
  {% endblock sidenav %}

{% block content %}

{% autoescape off%}

{{ content }}
{% endautoescape %}

<p>
  Page last update: {{ last_updated|date:"D d F Y" }}
</p>
{% endblock content %}

mfdw_site/quotes/templates/quotes/quote.html
{% extends "base.html" %}

{% block title %}Quote Request{% endblock title %}

{% block sidenav %}
  {% for page in  page_list %}
    <li><a href="{{ page.permalink }}">{{ page.title }}</a></li>
  {% endfor %}
{% endblock sidenav %}

{% block content %}
<h1>Quote Request</h1>

{% if submitted %}
  <p class="success">
    Your quote was submitted successfully. Thank you.
  </p>

{% else %}
  <form action"" enctype="multipart/form-data"method="post" novlidate>
  <table>
    {{ form.as_table }}
    <tr>
      <td>&nbsp;</td>
      <td><input type="submit" vallue="Submit"></td>
    </tr>
  </table>
  {% csrf_token %}
  </form>
{% endif %}
{% endblock content %}

mfdw_site/quotes/templates/quotes/quote_detail.html
{% extends "quotes/quote.html" %}

{% block title %}All Quotes{% endblock title %}

{% block content %}
<h1>Quote Detail</h1>

<table class="quote">
  <tr><td>ID:</td><td>{{ quote.id}}</td></tr>
  <tr><td>Name:</td><td>{{ quote.name}}</td></tr>
  <tr><td>Company:</td><td>{{ quote.company}}</td></tr>
  <tr><td>Email:</td><td>{{ quote.email}}</td></tr>
  <tr><td>Web Address:</td><td>{{ quote.web}}</td></tr>
  <tr><td>Job Description:</td><td>{{ quote.description}}</td></tr>
  <tr><td>Site Status:</td><td>{{ quote.get_sitestatus_display}}</td></tr>
  <tr><td>Priority</td><td>{{ quote.get_priority_display}}</td></tr>
  <tr><td>Submit Date:</td><td>{{ quote.submitted|date:"m-d-y"}}</td></tr>
  <tr><td>Quote Date:</td><td>{{ quote.quotedate|date:"m-d-y"|default:"pending" }}</td></tr>
  <tr><td>Quote Price:</td><td>{{ quote.quoteprice|default:"--" }}</td></tr>
</table>
<p><a href="../show">Back to quote list</a></p>
{% endblock content %}

mfdw_site/quotes/templates/quotes/quote_list.html
{% extends "quotes/quote.html" %}

{% block title %}All Quotes{% endblock title %}

{% block content %}
<h1>All Quotes</h1>

<table style="border-collapse">
  <tr class="quotehdr"><th>ID</th><th>Client Name</th>
    <th>Company</th><th>Submitted</th>
    <th>Quoted</th><th>Quote Price</th>
  </tr>
  {% for quote in all_quotes %}
    <tr class="quoterow {% cycle '' 'altrow' %}">
      <td><a href="show/{{ quote.id }}">{{ quote.id }}</a></td>
      <td>{{ quote.name }}</td>
      <td>{{ quote.company }}</td>
      <td>{{ quote.submitted|date:"m-d-y" }}</td>
      <td>{{ quote.quotedate|date:"m-d-y"|default:"pending" }}</td>
      <td>{{ quote.quoteprice|default:"--" }}</td>
    </tr>
  {% endfor %}
</table>
{% endblock content %}